on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */24 * * *" # every 24 hours
    
name: Repo
jobs:
  make:
    name: Reload the Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
          
      - name: Install dependencies with APT
        run: |
          sudo apt install xz-utils bzip2 zstd
          
      - name: Import GPG
        run: |
          echo -n "${{ secrets.GPG_SECKEY }}"| base64 --decode | gpg --import
          echo -n "${{ secrets.GPG_PUBKEY }}" | base64 --decode | gpg --import
          
      - name: Regen Repo
        run: |
          chmod +x repo.sh
          bash repo.sh
          
      - name: Commit To Repo
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: 'Add Automated Update'
          signoff: true
